#!/usr/bin/env zsh
#
# gets the current powerlevel10k style
#
# function p10kgetstyle() {

if [[ -f $POWERLEVEL9K_CONFIG_FILE ]]; then
  local lines=( "${(@f)"$(<$POWERLEVEL9K_CONFIG_FILE)"}" )
  if [[ ${(@M)lines:#(#b)*p10k-(*).zsh*} ]]; then
    echo $match[1]
  fi
fi

# }